### ISSUE TITLE
Práctica 2_Prototipo de Realidad Aumentada

### ISSUE THREAD

**Issue by dulce-blm** [SistemasTecTlaxiaco/diseno-de-prototipo-de-realidad-aumentada-equipo-nancy-brenda-belem#2]
[Practica 2_Prototipo de RA.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-prototipo-de-realidad-aumentada-equipo-nancy-brenda-belem/files/8126067/Practica.2_Prototipo.de.RA.pdf)

**Comment by DavidFeria01** [comment]
Puntos: 100
Porcentaje: 20
trabajo muy bien elaborado que cumple con todos los putos solicitados

**Comment by josealfredo79** [comment]
Bien hecho y revisado
